name: Greetings on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.2.0
        if: ${{ github.event.pull_request.merged == true }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Congrats on getting your first pull request merged!<br><br>![](https://media.giphy.com/media/l4KhQo2MESJkc6QbS/giphy.gif)"
